project_id = "ujywjnyeprpwksoneavd"

[functions.notify-new-products]
verify_jwt = false

[functions.notify-new-request]
verify_jwt = false

[functions.notify-request-status]
verify_jwt = false

[functions.create-customer]
verify_jwt = false

[functions.notify-request-confirmation]
verify_jwt = false

[functions.notify-order-approved]
verify_jwt = false
